import random
print ("Datorns första slag")
datorSlag1 = random.randint(1,6)
datorSlag2 = + random.randint(1,6)
blank = str (input(""))
print (datorSlag1)
print ("Datorns andra slag")
blank = str (input(""))
print (datorSlag2)
datorLiv = datorSlag2 + datorSlag1
print ("Datorns totala liv: " +str(datorLiv))
blank = str(input(""))
print("Ditt första slag")
spelarSlag1 = random.randint(1,6)
blank = str(input(""))
print(spelarSlag1)